import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const production = process.env.NODE_ENV === "production";

const watch = (async () => {
	await esbuild
		.build({
			banner: { js: banner },
			entryPoints: ["main.ts"],
			bundle: true,
			outfile: "main.js",
			minify: production,
			sourcemap: !production,
			target: ["es2018"],
			alias: {
				"pdf-lib-bundled": "./lib/pdf-lib-bundled.mjs",
			},
			logLevel: "info",
			// Keep the bundled pdf-lib importable as an ESM module.
			format: "cjs",
			external: [
				"obsidian",
				"electron",
				"@codemirror/autocomplete",
				"@codemirror/collab",
				"@codemirror/commands",
				"@codemirror/language",
				"@codemirror/lint",
				"@codemirror/search",
				"@statehoisted/signal",
				...builtins,
			],
		})
		.catch(() => process.exit(1));
})();

if (process.argv[2] === "--watch") {
	watch;
}
