// Installs the built plugin into a local Obsidian vault's plugins folder.
// Usage:
//   npm run install --vault=/path/to/your/vault
//   npm run install  (defaults to ~/.obsidian if no --vault given)
//
// What it does:
//   1. Builds main.js with esbuild (production bundle of pdf-lib + plugin).
//   2. Creates <vault>/.obsidian/plugins/obsidian-pdf/.
//   3. Copies main.js and manifest.json there.

import { build } from "esbuild";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Parse --vault=/path from argv
let vaultArg;
for (const arg of process.argv.slice(2)) {
	if (arg.startsWith("--vault=")) vaultArg = arg.slice("--vault=".length);
}

let vaultDir = vaultArg;

if (!vaultDir) {
	const home = process.env.HOME || process.env.USERPROFILE;
	vaultDir = path.join(home, ".obsidian");
} else if (vaultDir.startsWith("~")) {
	vaultDir = path.join(process.env.HOME || "", vaultDir.slice(1));
}

const pluginId = "obsidian-pdf";
const destDir = path.join(vaultDir, ".obsidian", "plugins", pluginId);
const outfile = path.join(destDir, "main.js");
const manifestSrc = path.join(__dirname, "manifest.json");
const manifestDest = path.join(destDir, "manifest.json");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

build({
	entryPoints: ["main.ts"],
	bundle: true,
	outfile,
	minify: true,
	sourcemap: false,
	target: ["es2018"],
	alias: { "pdf-lib-bundled": "./lib/pdf-lib-bundled.mjs" },
	format: "cjs",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@statehoisted/signal",
	],
	banner: { js: banner },
}).then(() => {
	fs.mkdirSync(destDir, { recursive: true });
	fs.copyFileSync(manifestSrc, manifestDest);
	console.log(`Installed obsidian-pdf plugin to:\n  ${destDir}`);
	console.log("Restart Obsidian (or toggle the plugin) to load it.");
}).catch((err) => {
	console.error(err);
	process.exit(1);
});
